name: Auto-merge Markdown-only PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_markdown_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check for non-Markdown file changes
      id: file_changes
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
        if grep -vqE '\.md$' changed_files.txt; then
          echo "::set-output name=non_md_files::true"
        else
          echo "::set-output name=non_md_files::false"
        fi

    - name: Merge PR if only Markdown files changed
      if: steps.file_changes.outputs.non_md_files == 'false'
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        script: |
          const pr_number = context.payload.pull_request.number;
          await github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr_number,
            merge_method: 'squash'
          });
