name: Demo to create automatic PR

on:
  push:
    branches:
      - seasons-source

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise PR
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-per-branch"
          base: seasons-source
          title: "Auto PR"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          body: |
            This is to show automatic PR creation
          token: ${{ secrets.GH_TOKEN }}
          delete-branch: true

      - name: Debug Commit Data
        uses: actions/github-script@v4
        with:
          script: |
            console.log(process.env.GIT_COMMIT_AUTHOR_NAME);
            console.log(process.env.GIT_COMMIT_AUTHOR_EMAIL);

      - name: Print PR number
        run: echo "PR number is ${{ steps.create-pr.outputs.pull-request-number }}"

      - name: Approve Pull Request
        if: steps.create-pr.outputs.pull-request-number != ''
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}

      - name: Merge Pull Request
        if: steps.create-pr.outputs.pull-request-number != ''
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}
          method: squash
