name: Auto Merge Markdown Pull Requests

on:
  pull_request:
    paths:
      - 'season-*.md'

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Download and install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh -y

      - name: Check for only markdown changes
        id: check_markdown
        run: |
          git fetch origin seasons-source
          FILES=$(git diff --name-only origin/seasons-source...HEAD -- 'season-*.md')
          if [ -z "$FILES" ]; then
            echo "::set-output name=markdown_only::false"
          else
            echo "::set-output name=markdown_only::true"
          fi

      - name: Auto-approve and merge
        if: steps.check_markdown.outputs.markdown_only == 'true'
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          gh pr merge $PR_NUMBER --auto --squash --delete-branch
          gh pr comment $PR_NUMBER --body "This pull request has been automatically approved and merged because it only contains changes to markdown files."

        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
