name: Auto-merge PRs on seasons-source

on:
  pull_request:
    branches:
      - seasons-source

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check if PR is mergeable
        uses: peter-evans/commit-validation@v2
        with:
          required-status-checks: context

      - name: Merge PR
        uses: peter-evans/merge-pull-request@v2
        with:
          merge-method: squash
          commit-message: "Merge pull request #${{ github.event.pull_request.number }}"

      - name: Close PR
        uses: peter-evans/close-pull-request@v2
