name: Auto Merge

on:
  pull_request:
    branches:
      - seasons-source

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Pull Request
        id: validate_pr
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "Checking PR #$PR_NUMBER"
          
          # Example validation: Check for specific patterns in PR title
          PR_TITLE=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")
          if [[ "$PR_TITLE" != *"fix"* ]]; then
            echo "::error::Pull Request title must include 'fix'"
            echo "::set-output name=approved::false"
            exit 1
          fi

          echo "::set-output name=approved::true"

      - name: Merge Pull Request if Approved
        if: steps.validate_pr.outputs.approved == 'true'
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "Merging PR #$PR_NUMBER"

          # Merge the pull request using GitHub API
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge \
            -d '{"merge_method":"squash"}'
