name: Auto Merge Markdown Pull Requests

on:
  pull_request:
    paths:
      - 'season-*.md'

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Check for only markdown changes
        id: check_markdown
        run: |
          FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          if echo "$FILES" | grep -qv '^season-.*\.md$'; then
            echo "::set-output name=markdown_only::false"
          else
            echo "::set-output name=markdown_only::true"
          fi

      - name: Auto-approve
        if: steps.check_markdown.outputs.markdown_only == 'true'
        uses: hmarr/auto-approve-action@v2.1.0
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Merge pull request
        if: steps.check_markdown.outputs.markdown_only == 'true'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash --admin --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Comment on pull request
        if: steps.check_markdown.outputs.markdown_only == 'true'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "This pull request has been automatically approved and merged because it only contains changes to markdown files."
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
