name: Combined Workflows

on:
  pull_request:
    branches:
      - seasons-source
    paths:
      - 'season-*.md'
  workflow_run:
    workflows: ["Combined Workflows"]
    types:
      - completed

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Download and install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Check for only markdown changes
        id: check_markdown
        run: |
          git fetch origin seasons-source
          if git diff-tree --no-commit-id --name-only -r origin/seasons-source HEAD | grep -q '^season-.*\.md$'; then
            echo "markdown_only=true" >> $GITHUB_ENV
          else
            echo "markdown_only=false" >> $GITHUB_ENV
          fi

      - name: Auto-approve and merge
        if: env.markdown_only == 'true'
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          gh pr merge $PR_NUMBER --auto --squash --delete-branch
          gh pr comment $PR_NUMBER --body "This pull request has been automatically approved and merged because it only contains changes to markdown files."
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Comment on pull request
        if: env.markdown_only == 'true'
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          gh pr comment $PR_NUMBER --body "This pull request has been automatically approved and merged because it only contains changes to markdown files."
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  convert_and_deploy:
    needs: auto_merge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout seasons-source branch
        uses: actions/checkout@v2
        with:
          ref: seasons-source

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create converted_html directory if not exists
        run: |
          if [ ! -d "converted_html" ]; then
            mkdir converted_html
          fi
        shell: bash

      - name: Convert Markdown to HTML
        run: |
          shopt -s nullglob
          for file in season-*.md; do
            python convertor.py "$file" "converted_html/$(basename "${file%.md}.html")" "$(basename "${file%.md}")"
          done
        shell: bash

      - name: Ensure converted_html directory is not empty
        run: |
          ls -l converted_html

      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: true

      - name: Copy converted files to master branch
        run: |
          shopt -s nullglob
          files=(converted_html/*)
          if [ ${#files[@]} -gt 0 ]; then
            cp -r converted_html/* seasons-html/
            git add seasons-html/
            git commit -m "Update HTML files"
            git push origin master
          else
            echo "No HTML files found in converted_html/"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
