name: Auto-merge Markdown-only PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_markdown_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for only Markdown changes in seasons-source branch
        id: check_markdown
        run: |
          git fetch origin seasons-source  # فراخوانی اطلاعات برنچ seasons-source
          git diff-tree --no-commit-id --name-only -r origin/seasons-source HEAD | grep -E '^season-.*\.md$'
          if [ $? -eq 0 ]; then
            echo "::set-output name=markdown_only::true"
          else
            echo "::set-output name=markdown_only::false"
          fi

      - name: Merge PR if only Markdown files changed
        if: steps.check_markdown.outputs.markdown_only == 'true'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            async function run() {
              const pr_number = context.payload.pull_request.number;
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr_number,
                merge_method: 'squash'
              });
            }
            run();
