name: Demo to create automatic PR

on:
  push:
    branches:
      - seasons-source

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise PR
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-per-branch"
          base: seasons-source
          title: "Auto PR"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          body: |
            This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true

      - name: Print PR number
        run: echo "PR number is ${{ steps.create-pr.outputs.pull-request-number }}"

      - name: Approve Pull Request
        if: steps.create-pr.outputs.pull-request-number != ''
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}

      - name: Merge Pull Request
        if: steps.create-pr.outputs.pull-request-number != ''
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}
          method: squash

  enableAutoMerge:
    needs: updateAuthor
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto Merge
        run: |
          pr_number=${{ needs.updateAuthor.outputs['create-pr'].pull-request-number }}
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}/merge \
          -d '{"merge_method":"squash"}'

  confirmAutoMerge:
    needs: enableAutoMerge
    runs-on: ubuntu-latest
    steps:
      - name: Confirm Auto Merge
        run: |
          pr_number=${{ needs.updateAuthor.outputs['create-pr'].pull-request-number }}
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}/auto_merge \
          -d '{"enabled":true}'
