name: Markdown File Check

on: [push, pull_request]

jobs:
  check-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Set up Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Check for non-Markdown file changes
        id: check_files
        run: |
          # Get the base and head SHA
          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
            BASE_SHA=$(jq -r .pull_request.base.sha "$GITHUB_EVENT_PATH")
            HEAD_SHA=$(jq -r .pull_request.head.sha "$GITHUB_EVENT_PATH")
          else
            BASE_SHA=$(git rev-parse HEAD^1)
            HEAD_SHA=$(git rev-parse HEAD)
          fi

          # Get a list of files changed in the pull request
          CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA)

          # Initialize a flag to false
          NON_MARKDOWN_CHANGED=false

          # Check each file
          for FILE in $CHANGED_FILES; do
            if [[ $FILE != *.md ]]; then
              NON_MARKDOWN_CHANGED=true
              echo "Non-Markdown file changed: $FILE"
              break
            fi
          done

          # Export the result
          echo "::set-output name=non_markdown_changed::$NON_MARKDOWN_CHANGED"

 
