name: Convert and Deploy

on:
  push:
    branches:
      - seasons-source

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout seasons-source branch
        uses: actions/checkout@v2
        with:
          ref: seasons-source

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create converted_html directory if not exists
        run: |
          if [ ! -d "converted_html" ]; then
            mkdir converted_html
          fi
        shell: bash

      - name: Convert Markdown to HTML
        run: |
          shopt -s nullglob
          for file in season-*.md; do
            python convertor.py "$file" "converted_html/$(basename "${file%.md}.html")" "$(basename "${file%.md}")"
          done
        shell: bash

      - name: Ensure converted_html directory is not empty
        run: |
          ls -l converted_html

      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: true

      - name: Copy converted files to master branch
        run: |
          shopt -s nullglob
          files=(converted_html/*)
          if [ ${#files[@]} -gt 0 ]; then
            cp -r converted_html/* seasons-html/
            git add seasons-html/
            git commit -m "Update HTML files"
            git push origin master
          else
            echo "No HTML files found in converted_html/"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
